Migrating to netstandard
Amyris/AmyrisBio pull request #4
Opened 2019-04-23 21:02 UTC by legezam

2019-04-24 07:23 UTC, legezam commented
Please note, if you still need to access windows registry from netcore, you can use [windows compatibility pack](https://www.nuget.org/packages/Microsoft.Windows.Compatibility) as an intermediary solution.

2019-05-21 20:38 UTC, chrismacklin commented
Is it possible to build this library in a configuration that supports both netstandard and projects that are still running on .NET framework ~4.6?  The problem with this PR as it stands is that to accept it, I must upgrade every one of our production F# applications together to dotnetcore, which is a large undertaking.

2019-05-21 21:28 UTC, daz10000 commented
On Tue, May 21, 2019 at 08:38:04PM +0000, Chris Macklin wrote:
If we target netstandard,  I believe it will still support 4.6 (as long as you aren't using platform specific features like accessing registry).  I have taken out some crazy legacy features that relied on the windows api

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

Darren

> Is it possible to build this library in a configuration that supports both netstandard and projects that are still running on .NET framework ~4.6?  The problem with this PR as it stands is that to accept it, I must upgrade every one of our production F# applications together to dotnetcore, which is a large undertaking.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Amyris/AmyrisBio/pull/4#issuecomment-494548988

2019-05-21 21:39 UTC, chrismacklin commented
Ah, thanks for the clarification.  I was having some issues getting things to build on top of this but with this insight I can see now that I'm looking at red herrings.  Once I can confirm that everything still builds on top of this port, then I can merge this and release a new version.

Why did you need to port this library to support the GSL compiler running on dotnetcore?

2019-05-21 21:45 UTC, daz10000 commented
> Ah, thanks for the clarification.  I was having some issues getting things to build on top of this but with this insight I can see now that I'm looking at red herrings.  Once I can confirm that everything still builds on top of this port, then I can merge this and release a new version.

Happy to help with any errors if you want to share.

> 
> Why did you need to port this library to support the GSL compiler running on dotnetcore?

Not strictly necessary for any one feature but we moved to netcore over a year ago and it greatly simplifies all the project files / tooling / cross platform support - also made it easier to set up CI.  It makes sending in more PRs for other features we haven't yet submitted a lot simpler.  It's worth it just for the new project files.  You also get warnings (runtime) if you use old style projects with netcore so better just to migrate everything

Darren

2019-05-21 21:59 UTC, chrismacklin commented
Got it, thanks for clarifying!  That significantly eases getting this merged.

2019-08-22 20:06 UTC, Yzupnick commented
@legezam, 
Thanks for porting this too. 

I was able to get all the dotnet standard versions working with our internal applications (on .NET 4.6).  However I ran into some issues when our applications used Amyris.Bio while GslCore used Dmx.Amyris.Bio

## Alternate upgrade ordering

   1. Upgrade AmyrisBio to dotnetstandard + FAKE5 (This PR)
   1. Release AmyrisBio
   1. Upgrade GslCore (include reference to AmyrisBio in the existing PR) 
   1. Release GslCore

What are your thoughts?

2019-08-22 20:09 UTC, Yzupnick requested changes
Looks great so far. 

I think this PR has gotten a little stale though. Would you mind rebasing on master? (The only conflict should be the Release Notes and Assembly.Fs) 

Thanks!

2019-08-22 20:09 UTC, Yzupnick commented on tests/AmyrisBio.Tests/testDnaops.fs
> +let refTestGenome = @"..\..\..\test_data\S288C.fsa" |> Amyris.Bio.utils.smashSlash
This test is passing for me, but do you know why this change had to happen?

2019-08-22 21:14 UTC, daz10000 commented
On Thu, Aug 22, 2019 at 01:09:48PM -0700, Chanan Zupnick wrote:
> Yzupnick requested changes on this pull request.
> 
> Looks great so far. 
> 
> I think this PR has gotten a little stale though. Would you mind rebasing on master? (The only conflict should be the Release Notes and Assembly.Fs) 
> 
> Thanks!
> 
> > @@ -5,7 +5,7 @@ open Amyris.Bio.dnaops
>  open Amyris.Bio.biolib
>  open Amyris.Bio.utils
>  
> -let refTestGenome = @"..\..\test_data\S288C.fsa" |> Amyris.Bio.utils.smashSlash
> +let refTestGenome = @"..\..\..\test_data\S288C.fsa" |> Amyris.Bio.utils.smashSlash
> 
> This test is passing for me, but do you know why this change had to happen?

Yes! - the netcore binary folder structure adds one more layer to the output, so instead of bin/Debug/Foo.dll you get bin/Debug/{architecture}/Foo.dll so the test data are one more level of redirect away.  In some implementations I have made the tests flexible enough to check both when searching to preserve backwards compatibility

2019-08-23 08:36 UTC, legezam commented
> 
> 
> Looks great so far.
> 
> I think this PR has gotten a little stale though. Would you mind rebasing on master? (The only conflict should be the Release Notes and Assembly.Fs)
> 
> Thanks!

Done! I have tested the build even with the latest .net core 3 prev 7 sdk.

2019-08-23 08:38 UTC, legezam commented
> 
> 
> @legezam,
> Thanks for porting this too.
> 
> I was able to get all the dotnet standard versions working with our internal applications (on .NET 4.6). However I ran into some issues when our applications used Amyris.Bio while GslCore used Dmx.Amyris.Bio
> ## Alternate upgrade ordering
> 
>     1. Upgrade AmyrisBio to dotnetstandard + FAKE5 (This PR)
> 
>     2. Release AmyrisBio
> 
>     3. Upgrade GslCore (include reference to AmyrisBio in the existing PR)
> 
>     4. Release GslCore
> 
> 
> What are your thoughts?

I would prefer this too.

2019-12-17 13:06 UTC, legezam commented
@Yzupnick , i have added further upgrades:
- migrated to netstandard2.1 + netcoreapp3.1
- removed manual handling of tool restoration and introduced tool manifest
- updated dependencies

please review

2019-12-17 13:09 UTC, legezam commented on src/AmyrisBio/utils.fs
> +        |> Seq.filter (fun name -> List.exists (fun (suffix : string) -> name.EndsWith(suffix)) suffixList)
please note, string.EndsWith received new overloads in netstandard2.1 making the compiler complain about ambiguity. This type annotation resolves that ambiguity

2020-01-21 19:27 UTC, Yzupnick commented
We are ready internally for this!

Thanks for your patience. I am going to do one final review today and if everything looks good/still works I will publish the latest Nuget tomorrow.
I will also be bumping the major version of the Nuget package to 3.0. Does that work for you?

2020-01-21 19:57 UTC, daz10000 commented
Congrats and yes on version bump. Thanks!  We should celebrate 

Von meinem iPhone gesendet

> Am 21.01.2020 um 11:27 AM schrieb Chanan Zupnick <notifications@github.com>:
> 
> ﻿
> We are ready internally for this!
> 
> Thanks for your patience. I am going to do one final review today and if everything looks good/still works I will publish the latest Nuget tomorrow.
> I will also be bumping the major version of the Nuget package to 3.0. Does that work for you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-01-22 18:47 UTC, merged